### ISSUE TITLE
Bug on Freebie Points

### ISSUE THREAD

**Issue by heltonteixeira** [DrSharky/VTMsite#111]
There is a issue on freebies points, I'll just put the steps to reproduce it.

- Open a new sheet
- Put any quantity of points on any Discipline
- Toggle Freebie Mode
- Put 2 points on the same Discipline added early
- Remove the the freebie from that Discipline clicking on the first dot (not the last one)

You will end up with extra 7 points, and it can be repeated undefined.

**Comment by DrSharky** [comment]
Thanks for opening, I'll get to it!
