### ISSUE TITLE
Allow free point spending

### ISSUE THREAD

**Issue by OttMatiisen** [DrSharky/VTMsite#120]
Mainly needed for StoryTellers for making NPCs who are older and more experienced than the standard new character. Also for players for the same reason.

**Comment by DrSharky** [comment]
This is a feature that I intend on adding eventually. Right now I'm working on improving the layout, and adding a glossary page possibly. Once that's done I want to add a page for creation without the beginning restrictions. Possibly even add a page for awarding xp, but one step at a time for now. Thanks for letting me know this is a desired feature, I'll keep it open and put it on my to-do list!
